import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { WixClientContextProvider } from "@/context/wixContext";

const integralcf = localFont({ 
  src: '../public/fonts/Fontspring-DEMO-integralcf-bold.otf', 
  variable: "--font-integralcf", 
  weight: '700' 
});

const satoshi = localFont({
  src: [
    {
      path: '../public/fonts/Satoshi-Regular.woff', 
      weight: '400'
    },
    {
      path: '../public/fonts/Satoshi-Medium.woff', 
      weight: '500'
    },
    {
      path: '../public/fonts/Satoshi-Bold.woff', 
      weight: '700'
    },
  ], 
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          `
          ${satoshi.className} 
          ${integralcf.variable}
          antialiased 
          flex 
          flex-col 
          h-screen
          justify-between`
      }
      >
        <WixClientContextProvider>
          <Header />
          <main className="flex-1 relative">
            {children}
          </main>
          <Footer />
        </WixClientContextProvider>
      </body>
    </html>
  );
}
